from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from typing import List
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

from .database import Base, engine, get_db
from .models import User, Route, EmissionHistory
from .routing_module import get_route_from_google, RoutingError
from .graph_routing import get_city_graph, get_route_from_graph
from .emission_model import load_emission_model, predict_co2_kg, EmissionModelNotTrained
from .eco_score import compute_eco_score
from .optimization import compare_routes
from .schemas import RouteRequest, RouteResponse, RouteOption, EmissionHistoryResponse
from .xai_engine import generate_explanation
from . import schemas

app = FastAPI(title="Eco Routing API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

Base.metadata.create_all(bind=engine)


@app.get("/health")
def health_check():
    return {"status": "ok"}


def get_or_create_user(db: Session, email: str | None) -> User | None:
    if not email:
        return None
    user = db.query(User).filter(User.email == email).first()
    if user:
        return user
    user = User(email=email)
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


@app.post("/api/routes/compute", response_model=RouteResponse)
def compute_routes(payload: RouteRequest, db: Session = Depends(get_db)):
    try:
        model = load_emission_model()
    except EmissionModelNotTrained as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    user = get_or_create_user(db, payload.user_email)

    mode_map = {
        "car": "driving",
        "bike": "bicycling",
        "ev": "driving",
        "walking": "walking",
        "metro": "transit",
        "bus": "transit",
        "auto": "driving",
    }

    options: List[RouteOption] = []
    
    # Try to load graph if a classical algorithm is requested
    G = None
    if payload.algorithm in ["dijkstra", "astar", "multi_objective"]:
        try:
            G = get_city_graph()
            # Need to geocode origin and destination strings to lat/lng
            from geopy.geocoders import Nominatim
            geolocator = Nominatim(user_agent="eco_routing_app")
            orig_loc = geolocator.geocode(payload.origin)
            dest_loc = geolocator.geocode(payload.destination)
            if not orig_loc or not dest_loc:
                 raise HTTPException(status_code=400, detail="Could not geocode origin or destination")
        except Exception as e:
            print(f"Error initializing local graph routing: {e}")
            raise HTTPException(status_code=500, detail="Local graph routing not available")

    for mode in payload.modes:
        google_mode = mode_map[mode]
        route_data = None
        
        try:
            if payload.algorithm in ["dijkstra", "astar", "multi_objective"] and G is not None:
                # Use local graph for routing
                # Note: Currently uses the drive network for all modes as a baseline
                metrics = get_route_from_graph(
                    G, 
                    orig_loc.latitude, orig_loc.longitude, 
                    dest_loc.latitude, dest_loc.longitude, 
                    payload.algorithm
                )
                
                # Format to match google_route_data
                import polyline
                encoded_polyline = polyline.encode([(pt["lat"], pt["lng"]) for pt in metrics["polyline"]])
                
                route_data = {
                    "origin": payload.origin,
                    "destination": payload.destination,
                    "distance_km": metrics["distance_km"],
                    "duration_min": metrics["duration_min"],
                    "duration_in_traffic_min": metrics["duration_min"], # Local graph doesn't have real-time traffic yet
                    "traffic_delay_min": 0.0,
                    "polyline": encoded_polyline,
                    "steps": [], # Detailed steps not generated by basic local graph yet
                    "raw": {}
                }
            else:
                # Fallback to Google Maps API
                route_data = get_route_from_google(
                    payload.origin,
                    payload.destination,
                    google_mode,
                    use_traffic=True,
                )
        except RoutingError as exc:
            # Skip this mode if Google doesn't find a result
            print(f"Skipping mode {mode} due to error: {exc}")
            continue
        except Exception as exc:
            print(f"Algorithm {payload.algorithm} failed for mode {mode}: {exc}")
            continue

        distance_km = route_data["distance_km"]
        duration_in_traffic_min = route_data["duration_in_traffic_min"]
        traffic_delay_min = route_data["traffic_delay_min"]

        avg_speed_kmh = (
            (distance_km / (duration_in_traffic_min / 60.0))
            if duration_in_traffic_min > 0
            else 0.0
        )

        fuel_type = payload.fuel_type
        vehicle_type = payload.vehicle_type
        
        # Override based on the selected icon mode
        if mode == "ev":
            fuel_type = "electric"
            vehicle_type = "ev"
        elif mode == "auto":
            fuel_type = "cng"
            vehicle_type = "auto"
        elif mode == "bus":
            fuel_type = "diesel"  # Bangalore buses are mostly diesel/cng/electric, diesel is a safe baseline
            vehicle_type = "bus"
        elif mode in {"walking", "metro", "bike"}:
            fuel_type = "none"
            vehicle_type = mode

        co2_kg = predict_co2_kg(
            model,
            distance_km=distance_km,
            avg_speed_kmh=avg_speed_kmh,
            vehicle_type=vehicle_type,
            fuel_type=fuel_type,
            traffic_delay_min=traffic_delay_min,
            elevation_gain_m=payload.elevation_gain_m,
        )
        
        # Ensure zero emissions for human-powered modes for presentation clarity
        if mode in {"walking", "bike"}:
            co2_kg = 0.0

        eco_score = compute_eco_score(
            co2_kg=co2_kg,
            traffic_delay_min=traffic_delay_min,
            distance_km=distance_km,
        )

        route_option = RouteOption(
            mode=mode,
            distance_km=distance_km,
            duration_min=route_data["duration_min"],
            duration_in_traffic_min=duration_in_traffic_min,
            traffic_delay_min=traffic_delay_min,
            polyline=route_data["polyline"],
            co2_kg=co2_kg,
            eco_score=eco_score,
            steps=route_data.get("steps", []),
        )
        options.append(route_option)

        db_route = Route(
            user_id=user.id if user else None,
            origin=route_data["origin"],
            destination=route_data["destination"],
            mode=mode,
            distance_km=distance_km,
            duration_min=route_data["duration_min"],
            duration_in_traffic_min=duration_in_traffic_min,
            eco_score=eco_score,
            co2_kg=co2_kg,
        )
        db.add(db_route)
        db.commit()
        db.refresh(db_route)

        db_emission = EmissionHistory(
            user_id=user.id if user else None,
            route_id=db_route.id,
            mode=mode,
            distance_km=distance_km,
            duration_min=route_data["duration_min"],
            traffic_delay_min=traffic_delay_min,
            co2_kg=co2_kg,
            eco_score=eco_score,
        )
        db.add(db_emission)
        db.commit()

    if not options:
        raise HTTPException(
            status_code=404, 
            detail="No valid routes found for any of the selected modes."
        )

    fastest = min(options, key=lambda o: o.duration_in_traffic_min)
    eco_optimized = max(options, key=lambda o: o.eco_score)

    comparison_metrics = compare_routes(
        fastest_route=fastest.dict(),
        eco_route=eco_optimized.dict(),
    )

    origin = options[0].mode and payload.origin
    destination = options[0].mode and payload.destination

    return RouteResponse(
        origin=origin,
        destination=destination,
        options=options,
        comparison={
            "fastest": fastest,
            "eco_optimized": eco_optimized,
            **comparison_metrics,
        },
    )


@app.get("/api/emissions/history", response_model=EmissionHistoryResponse)
def get_emission_history(
    user_email: str | None = None,
    db: Session = Depends(get_db),
):
    query = db.query(EmissionHistory)
    if user_email:
        user = db.query(User).filter(User.email == user_email).first()
        if not user:
            return {"items": []}
        query = query.filter(EmissionHistory.user_id == user.id)

    items = query.order_by(EmissionHistory.created_at.desc()).limit(100).all()
    return {"items": items}


@app.post("/api/xai/chat", response_model=schemas.XAIChatResponse)
def chat_with_assistant(payload: schemas.XAIChatRequest):
    try:
        explanation = generate_explanation(payload.route_context, payload.message)
        return schemas.XAIChatResponse(response=explanation)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"XAI Engine Error: {e}")

